name: TryHackMe Badge Workflow

on:
  schedule:
    # Make it run every 24 hours
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's TryHackMe badge with the latest TryHackMe image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@1.0.0
        with:
          # Replace with your TryHackMe username
          username: "<SunKyu>"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Do not paste your GitHub token here - this is a placeholder
                                                  # and will pull your GitHub token automatically
